### ISSUE TITLE
Fixxx

### ISSUE THREAD

**Issue by HirziGamingYT** [Chitandaa/Acchi#1]
Woi ada bugg njirr xd

**Comment by Chitandaa** [comment]
> Woi ada bugg njirr xd

Bug apa woi

**Comment by HirziGamingYT** [comment]
> woi

Tapi boonk eaaa

**Comment by Chitandaa** [comment]
> > woi
> 
> Tapi boonk eaaa

Bjir, ngetest di repo gw, gw close yah?
